### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple' 

### ISSUE THREAD

**Issue by nolehuan** [OSU-Haolin/Pedestrian_Crossing_Intention_Prediction#10]
Hi!I ran "python train_test.py -c config_files/ours/MASK_PCPA_jaad_2d.yaml" but got this TypeError: 

```
Traceback (most recent call last):
  File "train_test.py", line 210, in <module>
    run(config_file=config_file)
  File "train_test.py", line 154, in run
    model_opts=configs['model_opts'])
  File "/home/buaa/桌面/lh/Pedestrian_Crossing_Intention_Prediction/action_predict.py", line 1060, in train
    callbacks=callbacks)
  File "/home/buaa/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/buaa/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 224, in fit
    distribution_strategy=strategy)
  File "/home/buaa/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 547, in _process_training_inputs
    use_multiprocessing=use_multiprocessing)
  File "/home/buaa/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 606, in _process_inputs
    use_multiprocessing=use_multiprocessing)
  File "/home/buaa/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 613, in __init__
    output_shapes=nested_shape)
  File "/home/buaa/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 540, in from_generator
    output_types, tensor_shape.as_shape, output_shapes)
  File "/home/buaa/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/data/util/nest.py", line 471, in map_structure_up_to
    results = [func(*tensors) for tensors in zip(*all_flattened_up_to)]
  File "/home/buaa/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/data/util/nest.py", line 471, in <listcomp>
    results = [func(*tensors) for tensors in zip(*all_flattened_up_to)]
  File "/home/buaa/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 1216, in as_shape
    return TensorShape(shape)
  File "/home/buaa/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 776, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/home/buaa/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 776, in <listcomp>
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/home/buaa/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 718, in as_dimension
    return Dimension(value)
  File "/home/buaa/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 193, in __init__
    self._value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple' 
```
What do you think caused the error?
thank you!

**Comment by OSU-Haolin** [comment]
So first, try not to include Chinese character (e.g 桌面) in your project path. I will try to pinpoint the problem this weekend and then reply you here.

**Comment by OSU-Haolin** [comment]
It is hard to pinpoint the problem. Please check the details (trained model, configs, parameters, etc) for test stream.

**Comment by sgt390** [comment]
I had the same error while using tensorflow-gpu v. 2.0. I fixed the problem by upgrading to tensorflow-gpu v.2.2
