### ISSUE TITLE
file error

### ISSUE THREAD

**Issue by aoteman233** [OSU-Haolin/Pedestrian_Crossing_Intention_Prediction#12]
Hello, how can I solve this problem? The data set and annotations of jaad are set up as required.
2021-12-16 20:08:19.367831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2021-12-16 20:08:19.369866: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-12-16 20:08:19.375950: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2021-12-16 20:08:19.379667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2021-12-16 20:08:19.381758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4096 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 960M, pci bus id: 0000:02:00.0, compute capability: 5.0)
[--------------------] 0.00% 2021-12-16 20:08:22.955776: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-12-16 20:08:26.104307: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: Invoking GPU asm compilation is supported on Cuda non-Windows platforms only
Relying on driver to perform ptx compilation.
Modify $PATH to customize ptxas location.
This message will be only logged once.
2021-12-16 20:08:26.437737: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
Traceback (most recent call last):
  File "train_test.py", line 209, in <module>
    run(config_file=config_file)
  File "train_test.py", line 152, in run
    saved_files_path = method_class.train(beh_seq_train, beh_seq_val, **configs['train_opts'],
  File "F:\CODE\PCIP\action_predict.py", line 1035, in train
    data_train = self.get_data('train', data_train, {**model_opts, 'batch_size': batch_size})
  File "F:\CODE\PCIP\action_predict.py", line 5457, in get_data
    features, feat_shape = self.get_context_data(model_opts_3d, data, data_type, d_type)
  File "F:\CODE\PCIP\action_predict.py", line 818, in get_context_data
       return self.load_images_crop_and_process(data['image'],
  File "F:\CODE\PCIP\action_predict.py", line 458, in load_images_crop_and_process
        with open(img_save_path, 'wb') as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'data/features\\jaad\\local_context_cnn_vgg_raw_1.5\\.\\JAAD\\images\\video_0001\\00491_0_1_3b.pkl'
![Uploading 屏幕截图 2021-12-16 194323.png…]()

**Comment by OSU-Haolin** [comment]
Which platform you use for running code? Linux or Windows. If you use Windows, it may cause path error and you need to revise the file path in Windows format.

**Comment by aoteman233** [comment]
> Which platform you use for running code? Linux or Windows. If you use Windows, it may cause path error and you need to revise the file path in Windows format.

thank you very much for your reply.
yes i use windows ,how can i revise the file path ? i am a rookie

**Comment by OSU-Haolin** [comment]
> > Which platform you use for running code? Linux or Windows. If you use Windows, it may cause path error and you need to revise the file path in Windows format.
> 
> thank you very much for your reply. yes i use windows ,how can i revise the file path ? i am a rookie

I cannot pinpoint the position because I never try the code in Windows. I think first you should trace the error message (or Debug) and find where the program calls the path. Then, search in Google and find the path difference between the windows python and Linux python is a fast way to solve the problem. If you have new issue, let me know here.

**Comment by aoteman233** [comment]
> > > 您使用哪个平台来运行代码？Linux 或 Windows。如果使用Windows，可能会导致路径错误，需要修改Windows格式的文件路径。
> > 
> > 
> > 非常感谢您的回复。是的，我使用的是 Windows，如何修改文件路径？我是菜鸟
> 
> 我无法确定位置，因为我从未在 Windows 中尝试过代码。我认为首先您应该跟踪错误消息（或调试）并找到程序调用路径的位置。然后，在Google中搜索并找到windows python和Linux python之间的格式差异是一种快速解决问题的方法。如果您有新问题，请在此处告诉我。

thank you ,i will try
